create-nvme: Update the XML generated to address changes in QEMU/Libvirt
When moving to Ubuntu 24.04 I noticed that the libvirt XML generated
no longer works. I assume this is due to some update in either QEMU or
libvirt itself. Now we get error messages of the sort:

batesste@snoc-pinewood:~$ virsh start batesste-test-vm
error: Failed to start domain 'batesste-test-vm'
error: internal error: QEMU unexpectedly closed the monitor
(vm='batesste-test-vm'): 2024-11-09T20:58:02.900957Z
qemu-system-x86_64: -device
nvme,drive=nvme1,serial=nvme1,cmb_size_mb=0,bus=pcie.0,addr=6: PCI:
slot 6 function 0 not available for nvme, in use by nvme,id=(null)

It looks like adding somerthing like

bus=pcie.0,addr=7

to the --device nvme line fixes this. I may want to root cause as to
why. Note each NVMe device needs a different addr.

Fixes #40.